### ISSUE TITLE
Easier way to customize mappings?

### ISSUE THREAD

**Issue by mracos** [tknightz/telescope-termfinder.nvim#1]
Hi! 👋 

First of all, thank you so much for this extension, it was exactly what I was looking for. 😄 
Maybe I'm being #lazyweb but since you just wrote this extension it might be fresh on your head.

I'm really used to `<C-n>` to move selections down so I tried to override the mapping defined [here](https://github.com/tknightz/telescope-termfinder.nvim/blob/master/lua/telescope/_extensions/termfinder/main.lua#L41) to be back to be the default one. I also tried to add a new mapping `<C-r>` that would be this "term rename" action.

I've mapped the function below to a mapping but **maybe there's an easier way that I'm missing?**

```lua
telescope.extensions.termfinder.find({
  attach_mappings = function(_prompt_bfnr, map)
    map("i", "<c-r>", require("telescope._extensions.termfinder.actions").rename_term)
    map("i", "<c-n>", require("telescope.actions").move_selection_next)
                                                                                       
    return true
  end
})
```

**Comment by tknightz** [comment]
@mracos Hey! I've just updated it. You can customize mappings from `telescope.nvim` config file now.

**Comment by mracos** [comment]
Thanks for the quick response! Worked flawlessly. 💙

**Comment by TamaMcGlinn** [comment]
`<C-n>` as a default mapping is insane. What, do you expect us to reach over to the arrow keys to go up/down the list?
